// src/main.rs

mod generator;

use clap::{Parser, Subcommand};
use std::{env, fs};
use dialoguer::{Select, theme::ColorfulTheme};
use anyhow::Result;
use crate::generator::{Framework, Auth, generate_env};

#[derive(Parser)]
#[command(name = "forge", about = "Opinionated env & config generator")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    Init,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Init => {
            run_init()?;
        }
    }

    Ok(())
}

fn run_init() -> Result<()> {
    let theme = ColorfulTheme::default();

    let framework = match Select::with_theme(&theme)
        .with_prompt("Choose a framework")
        .items(&["Next.js", "Express"])
        .default(0)
        .interact()?
    {
        0 => Framework::NextJs,
        _ => Framework::Express,
    };

    let auth = match Select::with_theme(&theme)
        .with_prompt("Choose auth type")
        .items(&["None", "JWT"])
        .default(0)
        .interact()?
    {
        0 => Auth::None,
        _ => Auth::Jwt,
    };

    let cwd = env::current_dir()?;
    let project_dir = cwd.join("forge-project");

    fs::create_dir_all(&project_dir)?;

    // .env.example
    fs::write(
        project_dir.join(".env.example"),
        generate_env(&framework, &auth),
    )?;

    // docker-compose.yml
    fs::write(
        project_dir.join("docker-compose.yml"),
        r#"version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: applocal
    ports:
      - "5432:5432"
"#,
    )?;

    // README.md
    let readme = format!(
        r#"# Forge Project

This folder was generated by **forge**.

## Selected stack

- Framework: {:?}
- Auth: {:?}
- Database: Postgres (Docker)

## Environment variables

See `.env.example`. Copy it to `.env` and fill values.

Key vars:
- `DATABASE_URL` – Postgres connection string
- `JWT_SECRET` (if JWT enabled) – secret key for signing tokens
- `PORT` / `NEXT_PUBLIC_API_URL` – service URLs and ports

## Docker

Run Postgres locally:
"#,
        framework, auth
    );

    fs::write(project_dir.join("README.md"), readme)?;

    println!(" Forge project created at {:?}", project_dir);
    println!(" Framework: {:?}, Auth: {:?}", framework, auth);

    Ok(())
}
